#!/bin/bash

function cmd_help
{
    if [ "$1" = "" ]; then
        help_help
    elif [ "$1" = "-v" ]; then
        #all help functions
        echo
    else
        while [ "$1" != "" ]; do
            #case "$1" in 
            #[cC]ommand ) help_function;;
            #* ) problem_encountered "Not a valid command";;
            #esac
            shift
        done
    fi
}

function help_help
{
    echo "This is of no help right now"
}

#called to end script in error
function problem_encountered
{
    if [ "$1" != "" ]; then
        echo "$1" >&2
    fi
    #clean_up
    echo 'type "help" for usage page' >&2
    exit 1
}

# function clean_up
# {
# }

#called to end the script with success
function script_done
{
    #clean_up
    echo "done"
    exit 0
}

 function cmd_verify
 {
    #Verify an APK:
    #$ jarsigner -verify –verbose [-certs] theapp.apk
    echo "verify"
 }
 
 function cmd_resign
 {
   #SIGN AN APK:
   #$ jarsigner -verbose –keystore ~/Publishing/Resources/something.keystore unsigned.apk "alias"

#setup and parse args
# Keystore Pass (...)
# PrivateKey Pass (...)

   echo "resign"
 }
 
function cmd_zipalign
{
  #make sure that the apk is signed??????
  # ZIPALIGN THE SIGNED APK
  # 
  # $ zipalign -v 4 "signed.apk" "signed-zipaligned.apk"
  echo "zipalign"
}


#Install
#if jarsign and/or zipalign are not in any folders in the path, put them in /usr/bin



###MAIN###

cmd="$1"
#bd="$(pwd)"

#if there was no command, exit
if [ "$cmd" = "" ]; then
    problem_encountered "no command"
else
    shift
fi

#if cmd was "help" or "h" show the usage page
if [ "$cmd" = "help" -o "$cmd" = "h" ]; then 
    cmd_help "$@"
    script_done
fi

#Commands

if [ "$cmd" = "verify" -o "$cmd" = "v" ]; then
    cmd_verify "$@"
    script_done
elif [ "$cmd" = "resign" -o "$cmd" = "r" ]; then
    cmd_resign "$@"
    script_done
elif [ "$cmd" = "zipalign" -o "$cmd" = "z" ]; then
    cmd_zipalign "$@"
    script_done
fi

#verify -verbose? the.apk

#resign the.apk

#zipalign or just align or something 





